import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

public class Manager extends Employee {
    private ManagerType managerType;
    private List<News> managedNews;

    public Manager(String id, String firstName, String lastName, String email,
                   String password, Language language, String employeeId,
                   double salary, String department, ManagerType managerType) {
        super(id, firstName, lastName, email, password, language, employeeId, salary, department);
        this.managerType = managerType;
        this.managedNews = new ArrayList<>();
    }

    // Назначить преподавателю курс
    public void assignCourse(Teacher teacher, Course course) {
        if (teacher != null && course != null) {
            teacher.manageCourse(course);
        }
    }

    // Одобрить регистрацию студента на курс
    public void approveRegistration(Student student, Course course) {
        if (student != null && course != null) {
            // Проверить ограничения
            if (student.getTotalCredits() + course.getCredits() <= 21) {
                student.registerForCourse(course);
            } else {
                throw new CourseOverloadException("Student would exceed 21 credits");
            }
        }
    }

    // Добавить курс для регистрации (мейджор/минор/фри элективный)
    public void addCourseForRegistration(Course course) {
        if (course != null) {
            // Логика добавления курса в реестр регистрации
            // В упрощённой версии просто отмечаем, что курс доступен
        }
    }

    // Создать статистический отчёт по успеваемости
    public String createStatisticalReport() {
        StringBuilder report = new StringBuilder();
        report.append("=== Academic Performance Report ===\n");
        report.append("Report generated by: ").append(firstName).append(" ").append(lastName).append("\n");
        report.append("Department: ").append(department).append("\n");
        return report.toString();
    }

    // Управлять новостями (добавление, закрепление)
    public void manageNews(News news) {
        if (news != null && !managedNews.contains(news)) {
            managedNews.add(news);
        }
    }

    // Закрепить новость (если это о Research)
    public void pinResearchNews(News news) {
        if (news != null && news.getTopic() != null && news.getTopic().equals("Research")) {
            news.pin();
        }
    }

    // Посмотреть запросы от сотрудников
    public List<Request> viewEmployeeRequests() {
        // В полной реализации это должно быть из DataStorage
        return new ArrayList<>();
    }

    // Получить студентов, отсортированных по GPA
    public List<Student> getStudentsSortedByGpa(List<Student> students) {
        if (students == null || students.isEmpty()) {
            return new ArrayList<>();
        }
        List<Student> sorted = new ArrayList<>(students);
        sorted.sort(Comparator.comparingDouble(Student::getGpa).reversed());
        return sorted;
    }

    // Получить студентов, отсортированных по имени
    public List<Student> getStudentsSortedByName(List<Student> students) {
        if (students == null || students.isEmpty()) {
            return new ArrayList<>();
        }
        List<Student> sorted = new ArrayList<>(students);
        sorted.sort(Comparator.comparing(Student::getFirstName)
                .thenComparing(Student::getLastName));
        return sorted;
    }

    public ManagerType getManagerType() {
        return managerType;
    }

    @Override
    public String toString() {
        return "Manager{" +
                "id='" + id + '\'' +
                ", name='" + firstName + " " + lastName + '\'' +
                ", managerType=" + managerType +
                ", department='" + department + '\'' +
                '}';
    }
}
