import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

public class Manager extends Employee {

    private ManagerType managerType;

    public Manager(String id, String firstName, String lastName, String email,
                   String password, Language language, String employeeId,
                   double salary, String department, ManagerType managerType) {
        super(id, firstName, lastName, email, password, language, employeeId, salary, department);
        this.managerType = managerType;
    }

    public void assignCourse(Teacher teacher, Course course) {
        if (teacher != null && course != null) {
            teacher.manageCourse(course);
        }
    }

    public void approveRegistration(Student student, Course course) {
        if (student == null || course == null) return;
        if (student.getTotalCredits() + course.getCredits() > 21) {
            throw new CourseOverloadException("Student would exceed 21 credits");
        }
        student.registerForCourse(course);
    }

    public void addCourseForRegistration(Course course) {
        if (course != null) {
            System.out.println("[Manager] Course added for registration " + course);
        }
    }

    public String createStatisticalReport() {
        StringBuilder sb = new StringBuilder();
        sb.append("=== Academic Performance Report ===\n");
        sb.append("Generated by ").append(firstName).append(" ").append(lastName).append("\n");
        sb.append("Department ").append(department).append("\n");
        sb.append("Report Date ").append(new java.util.Date()).append("\n\n");

        // Get all students and compute statistics
        List<User> allUsers = DataStorage.getInstance().getUsers();
        List<Student> students = new ArrayList<>();

        for (User u : allUsers) {
            if (u instanceof Student && !(u instanceof GraduateStudent)) {
                students.add((Student) u);
            }
        }

        sb.append("Total Students ").append(students.size()).append("\n");

        if (!students.isEmpty()) {
            double totalGpa = 0;
            int totalCredits = 0;

            for (Student s : students) {
                totalGpa += s.getGpa();
                totalCredits += s.getTotalCredits();
            }

            sb.append("Average GPA ").append(String.format("%.2f", totalGpa / students.size())).append("\n");
            sb.append("Average Credits ").append(totalCredits / students.size()).append("\n");
        }

        return sb.toString();
    }

    // Adds the news to DataStorage and auto-pins if topic is Research
    public void manageNews(News news) {
        if (news == null) return;
        DataStorage.getInstance().addNews(news);
        if ("Research".equals(news.getTopic())) {
            news.pin();
        }
    }

    // Generates news about top cited researcher from DataStorage and stores it
    public void generateTopCitedResearcherNews() {
        Researcher top = DataStorage.getInstance().getTopCitedResearcher();

        if (top != null) {
            int hIndex = top.calculateHIndex();
            String name = "Unknown Researcher";

            // Extract name if this is TeacherResearcher wrapper
            if (top instanceof TeacherResearcher) {
                TeacherResearcher tr = (TeacherResearcher) top;
                Teacher t = tr.getTeacher();
                if (t != null) {
                    name = t.getFirstName() + " " + t.getLastName();
                }
            }

            String title = "Top Cited Researcher of the Year";
            String content = name + " with h-index " + hIndex +
                    " and " + top.getPapers().size() + " papers";

            News news = new News(title, content, "Research");
            manageNews(news);

            System.out.println("[NEWS] " + news);
        }
    }

    public List<Request> viewEmployeeRequests() {
        return DataStorage.getInstance().getRequests();
    }

    public List<Student> getStudentsSortedByGpa(List<Student> students) {
        if (students == null || students.isEmpty()) return new ArrayList<>();
        List<Student> sorted = new ArrayList<>(students);
        sorted.sort(Comparator.comparingDouble(Student::getGpa).reversed());
        return sorted;
    }

    public List<Student> getStudentsSortedByName(List<Student> students) {
        if (students == null || students.isEmpty()) return new ArrayList<>();
        List<Student> sorted = new ArrayList<>(students);
        sorted.sort(Comparator.comparing(Student::getFirstName)
                .thenComparing(Student::getLastName));
        return sorted;
    }

    @Override
    public String toString() {
        return "Manager{id='" + id + "', name='" + firstName + " " + lastName
                + "', type=" + managerType + ", dept='" + department + "'}";
    }
}